from github import Github, Repository
from models import PlanOutput, CodeChanges, SecurityReport, PRResult


def run_pr_creator(
    github_client: Github,
    repo: Repository,
    plan: PlanOutput,
    changes: CodeChanges,
    security_report: SecurityReport,
    ticket: dict,
    test_attempts: int,
    test_output: str
) -> PRResult:

    ticket_id = ticket["id"]

    # ── PR Deduplication Logic ─────────────────────────────────────────────────
    open_prs = list(repo.get_pulls(state="open"))
    for existing_pr in open_prs:
        pr_title = existing_pr.title
        pr_branch = existing_pr.head.ref

        same_ticket = pr_title.startswith(ticket_id)
        same_branch = pr_branch == plan.branch_name

        if same_ticket and same_branch:
            # Exact re-run - auto close and replace
            existing_pr.edit(state="closed")
            try:
                repo.get_git_ref(f"heads/{pr_branch}").delete()
            except Exception:
                pass
            print(f"    Replaced existing PR #{existing_pr.number} for {ticket_id} (re-run detected)")

        elif same_ticket and not same_branch:
            # Same ticket, different branch - ask user what to do
            print(f"\n    ⚠️  WARNING: Open PR #{existing_pr.number} already exists for {ticket_id}")
            print(f"    ⚠️  Existing PR branch: {pr_branch}")
            print(f"    ⚠️  New branch:         {plan.branch_name}")
            print(f"    ⚠️  PR title:           {existing_pr.title}")
            print()

            while True:
                choice = input(
                    f"    This looks like a duplicate. What do you want to do?\n"
                    f"    [1] Close PR #{existing_pr.number} and create a fresh one\n"
                    f"    [2] Keep PR #{existing_pr.number} and create new PR alongside it\n"
                    f"    [3] Abort - do not create a new PR\n"
                    f"    Enter 1, 2, or 3: "
                ).strip()

                if choice == "1":
                    existing_pr.edit(state="closed")
                    try:
                        repo.get_git_ref(f"heads/{pr_branch}").delete()
                    except Exception:
                        pass
                    print(f"    Closed PR #{existing_pr.number} and deleted branch {pr_branch}")
                    break
                elif choice == "2":
                    print(f"    Keeping PR #{existing_pr.number}. Creating new PR alongside it.")
                    break
                elif choice == "3":
                    raise SystemExit("    Aborted by user. No PR created.")
                else:
                    print("    Invalid choice. Enter 1, 2, or 3.")

        # Different ticket ID = unrelated PR, leave it completely alone

    # ── Create Fresh Branch ────────────────────────────────────────────────────
    main_branch = repo.get_branch("main")
    base_sha = main_branch.commit.sha

    try:
        repo.get_git_ref(f"heads/{plan.branch_name}").delete()
    except Exception:
        pass

    repo.create_git_ref(ref=f"refs/heads/{plan.branch_name}", sha=base_sha)
    print(f"    Branch created: {plan.branch_name}")

    # ── Push Files ─────────────────────────────────────────────────────────────
    for filepath, new_content in changes.files.items():
        try:
            existing = repo.get_contents(filepath, ref=plan.branch_name)
            repo.update_file(
                path=filepath,
                message=f"update {filepath}",
                content=new_content,
                sha=existing.sha,
                branch=plan.branch_name
            )
        except Exception:
            repo.create_file(
                path=filepath,
                message=f"add {filepath}",
                content=new_content,
                branch=plan.branch_name
            )
        print(f"    Pushed: {filepath}")

    # ── Format PR Description ──────────────────────────────────────────────────
    if security_report.findings:
        findings_text = "\n".join(
            f"- **{f.severity}** `{f.file}`: {f.issue}"
            for f in security_report.findings
        )
    else:
        findings_text = "No findings."

    pr_body = f"""## {ticket_id}: {ticket['title']}

### Summary
{plan.plan_summary}

### Files Changed
{chr(10).join(f"- `{f}`" for f in changes.files.keys())}

### Acceptance Criteria
{chr(10).join(f"- [x] {c}" for c in ticket['acceptance_criteria'])}

### Test Results
✅ All tests **passed** (verification attempt {test_attempts}/3)

<details>
<summary>Pytest output</summary>

```
{test_output[-1500:]}
```
</details>

### Security Review
**Verdict: {security_report.verdict}**
{security_report.env_check}

{findings_text}

---
*Generated by Zenarai AI Agent*
*Closes {ticket_id}*
"""

    # ── Open PR ────────────────────────────────────────────────────────────────
    pr = repo.create_pull(
        title=f"{ticket_id}: {ticket['title']}",
        body=pr_body,
        head=plan.branch_name,
        base="main"
    )

    return PRResult(
        pr_url=pr.html_url,
        branch_name=plan.branch_name,
        pr_number=pr.number
    )
